### ISSUE TITLE
This example is useless. The hover selector has no effect since hover does nothing anyway if hover is not supported.

### ISSUE THREAD

**Issue by mousetail** [mdn/content#12400]
https://github.com/mdn/content/blob/d304a553b8c05629376dfc8b593364cd3128b07d/files/en-us/web/css/%40media/hover/index.md?plain=1#L36

[@media/hover](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover)

**Comment by himanshugarg** [comment]
Thanks for reporting. On which platform is there an inconsistency with the behavior documented on MDN and what are the changes suggested? The example seems to work fine for Firefox 91.5.0esr (64-bit) on Desktop:

![Recording 2022-01-26 at 06 43 35](https://user-images.githubusercontent.com/2392803/151086512-56c3647b-9a5c-4ea4-82ec-3c4de2c3a449.gif)

**Comment by mousetail** [comment]
Example works but the query selector has no effect in this situation. If a browser has hover it will apply a hover effect, but it it does not the hover effect is not applied but it's impossible to hover anyway

**Comment by hamishwillee** [comment]
How would you change it. We could make it plain text that shows either that hover is supported or not - some something like:

### HTML

```html
<span id="fred"></a>
```

### CSS

```css
#fred::after {
    content: "Hover not supported";
    text-indent: 0;
    display: block;
    line-height: initial; /* New content takes up original line height */
  }

@media (hover: hover) {
  #fred::after {
    content: "Hover is supported";
    text-indent: 0;
    display: block;
    line-height: initial; /* New content takes up original line height */
  }
}
```
