### ISSUE TITLE
Issue with "Cascade and inheritance": problem with line 999

### ISSUE THREAD

**Issue by tsnee** [mdn/content#13309]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

#### What information was incorrect, unhelpful, or incomplete?
A CSS sample includes this ruleset:
```css
/* specificity: 0033 */
div div .nav:nth-child(2) a:hover {
    border: 10px double black;
}
```
The specificity is incorrect: it should be 0034. However the text refers to the value of 33. One of the two `div`s should be removed to make the example consistent.

#### Specific section or headline?
File included at line 199 of files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
(`{{EmbedGHLiveSample("css-examples/learn/cascade/specificity-boxes.html", '100%', 800)}}`).

#### What did you expect to see?
```css
/* specificity: 0033 */
div .nav:nth-child(2) a:hover {
    border: 10px double black;
}
```

#### Did you test this? If so, how?
Yes, I removed one of the `div`s in the interactive editor and confirmed that the example still worked.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/295e508da72ff83272a3b1ffa69a72cfeffcebde
* Document last modified: 2022-02-01T03:06:25.000Z

</details>
