### ISSUE TITLE
Content bug: Recommend using  .constructor.name instead of deprecated CSSRule.type

### ISSUE THREAD

**Issue by iamzapata** [mdn/content#14431]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/CSSRule/type

## Specific page section or heading?

CSSRule.type

## What is the problem?

If you find yourself needing _distinguish_ between different types of **CSSRule** and `.type` is deprecated, `.constructor.name` is a good alternative. Taken from [[all] Can we start ignoring CSSRule.type? ](https://github.com/w3c/csswg-drafts/issues/4142)

## What did you expect to see?

An additional note (**if** is the correct place to do so) about what can be used instead to identify different rules.

**Comment by teoli2003** [comment]
Are you sure this has been implemented? Do you have an example where I could test it?

**Comment by sideshowbarker** [comment]
@iamzapata this is waiting on your response

**Comment by iamzapata** [comment]
Sorry for the delay. 

I came up with a simple test, it can be played with [here](https://codesandbox.io/s/css-rule-constructor-name-gribv7)

I tested this in on:
- Firefox **Version 98.0.2 (64-bit)**
- Chrome **Version 99.0.4844.83 (Official Build) (arm64)**
- Safari **Version 15.3 (17612.4.9.1.8)**

I'll put contents here as well.

In the `index.html` and the `styles.css` files there a several css rules that I extract by querying the document for stylesheets and looping over these stylesheets to get the css rules: 

```javascript
const sheets = Array.from(document.styleSheets);
const rules = sheets.map((sheet) => Array.from(sheet.cssRules)).flat();
```
After, I loop over the list of css rules and reference the constructor name of the rule, and I get a list of the CSSRules extracted, for this example, this is the list:

```javascript
rules.forEach((rule) => {
  console.log(rule.constructor.name);
});
```

- CSSStyleRule
- CSSImportRule
- CSSNamespaceRule
- CSSFontFaceRule
- CSSMediaRule
- CSSPageRule
- CSSKeyframesRule
- CSSCounterStyleRule
- CSSSupportsRule

`index.html`
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <style>
      ul {
        padding: 5px;
        margin: 10px;
        list-style: thumbs;
      }
    </style>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <h1>
      CSSRule Constructor Example
    </h1>

    <ul id="css-rule-list"></ul>

    <script src="main.js" defer></script>
  </body>
</html>
```

`main.js`

<pre>
let sheets = Array.from(document.styleSheets);
let rules = sheets.map((sheet) => Array.from(sheet.cssRules)).flat();

const list = document.getElementById("css-rule-list");
rules.forEach((rule) => {
  const li = document.createElement("li");
  const ruleElement = document.createElement("code");
  const constructorElement = document.createElement("code");
  ruleElement.innerHTML = rule + " --> ";
  constructorElement.innerHTML = rule.constructor.name;

  list.appendChild(li);
  li.appendChild(ruleElement);
  li.appendChild(constructorElement);

  console.log(`Rule Object: ${rule}`);
  <b>console.log(`Constructor: ${rule.constructor.name}</b>`);
});
</pre>

notice the  `rule.constructor.name` line above.

`styles.css`

```css
@import url("styles2.css") screen;
@namespace url(http://www.w3.org/1999/xhtml);

@font-face {
  src: url("styles2.css");
  fonta-family: "sans-serif";
  font-weight: 400;
  font-style: normal;
}

@media (min-width: 500px) {
  body {
    color: blue;
  }
}

@page {
  margin: 1cm;
}

@keyframes slidein {
  from {
    transform: translateX(0%);
  }

  to {
    transform: translateX(100%);
  }
}

@counter-style thumbs {
  system: cyclic;
  symbols: "\1F44D";
  suffix: " ";
}

@supports (display: grid) {
  div {
    display: grid;
  }
}

@document url("") {
  // Style your defined URLs page
}

@font-feature-values "Leitura Display Swashes" {
  @swash {
    fancy: 1;
  }
}

```

`styles2.css`

```css
html,
body {
  height: 100%;
}

```
