### ISSUE TITLE
Issue with "<easing-function>": unclear that `steps` applies to each segment of the animation

### ISSUE THREAD

**Issue by danfishgold** [mdn/content#1644]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function

#### What information was incorrect, unhelpful, or incomplete?
The documentation doesn't mention that `steps`, unlike the other possible values of `<easing-function>`, applies to each segment of the keyframes animation, rather than to its entire duration.

#### Specific section or headline?

_The steps() class of easing functions_

Note that this information (or a subset of it is also included in [animation-timing-function](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function)

#### What did you expect to see?

Some mention of this behavior when there's multiple stops in the animation.

#### Did you test this? If so, how?

```html
<div class="animation-1">steps(1, end)</div>
<div class="animation-3">steps(3, end)</div>
```

```css
div {
  font-weight: 700;
  animation: rgb 10s infinite;
}

div.animation-1 {
  animation-timing-function: steps(1, end);
}

div.animation-3 {
  animation-timing-function: steps(3, end);
}

@keyframes rgb{
  0% {
    color: #f00;
  }
  33.33% {
    color: #0f0;
  }
  66.66% {
    color: #00f;
  }
}
```

[see live demo](https://steps-example.glitch.me)

I was expecting `steps(3, end)` to use the 0% value (red) for a third of the animation duration, then the 33.33% value (green) for another third, and then the 66.67% value (blue) for the remaining third.

Instead `steps(3, end)` split _each segment_ of the animation into three parts (so 3 * 3 = 9 in total). In order to achieve my desired animation I had to use `steps(1, end)`.

https://user-images.githubusercontent.com/777023/105553700-8e1b2100-5d0e-11eb-9158-aff991d6e2d7.mov

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/easing-function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/easing-function/index.html
* Document last modified: 2021-01-09T13:41:23.000Z

</details>
