### ISSUE TITLE
Unable to get Rust example working

### ISSUE THREAD

**Issue by richsad** [mdn/content#17079]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

### What specific section or headline is this issue about?

Compiling our code to WebAssembly

### What information was incorrect, unhelpful, or incomplete?

Hi, I get an error following the Rust hello-wasm program. First I get an error because wasm_bingen isn't found. I have installed webpack. I am confused because the TOML file references wasm-bingen and the code uses wasm_bingen. I've tried all the combinations and still does not work. Also, the code itself generate the error in the Visual Code IDE on the declaration of pub fn greet saying it is an unsafe operation. If I add the unsafe keyword as in:

```rs
use wasm_bingen::prelude::*;

#[wasm_bingen]
extern {
    pub fn alert(s: &str);
}

#[wasm_bingen]
pub unsafe fn greet(name: &str) {
    alert(&format!("Hello, {}", name));
}
```

The Cargo.toml file looks like this:
```toml
[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["My Name <myname@myname.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/richsad/hello-wasm"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

```

### What did you expect to see?

I got the following error instead of working:

```
Error: Error during execution of `cargo metadata`:     Updating crates.io index
error: no matching package found
searched package name: `wasm_bindgen`
perhaps you meant:      wasm-bindgen
location searched: registry `crates-io`
required by package `hello-wasm v0.1.0 (/Users/richardsadowsky/source/rust/hello-wasm)`

```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/rust_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/rust_to_wasm/index.md
* Last commit: https://github.com/mdn/content/commit/bab6f551b835833ee784374da9c2039795fffaee
* Document last modified: 2022-06-06T02:38:56.000Z

</details>
