### ISSUE TITLE
Extra slashes at the start of src URLs at the first example

### ISSUE THREAD

**Issue by beeceemato** [mdn/content#20636]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

The following example has extra slashes at start of the URLs that point to the font files, preventing the markup from working:

```css
@font-face {
  font-family: "Open Sans";
  src: url("/fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
       url("/fonts/OpenSans-Regular-webfont.woff") format("woff");
}
```

### What did you expect to see?

```css
@font-face {
  font-family: "Open Sans";
  src: url("fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
       url("fonts/OpenSans-Regular-webfont.woff") format("woff");
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@font-face`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@font-face/index.md
* Last commit: https://github.com/mdn/content/commit/05a61497f79c7bf5ffaf8fe7d94b36d5a0b9626e
* Document last modified: 2022-09-09T05:52:16.000Z

</details>
