### ISSUE TITLE
CSS animation-composition example doesn't have brightness-pulse animation

### ISSUE THREAD

**Issue by ChloeLiang** [mdn/content#22097]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-composition

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

The article mentions "The filter property is affected by both animations, pulse and brightness-pulse.", but I don't see `brightness-pulse` animation defined anywhere in the example.

```css
.icon:hover {
  filter: blur(5px);
  animation: 3s infinite pulse;
  animation-composition: add;
}

@keyframes pulse {
  0% {
    filter: blur(10px);
  }
  100% {
    filter: blur(20px);
  }
}

```

### What did you expect to see?

Either remove `brightness-pulse` or add it in the example.
