### ISSUE TITLE
EmbedLiveSample macro using deprecated parameters

### ISSUE THREAD

**Issue by bsmth** [mdn/content#25005]
We have some flaws raised about use of deprecated macro params:

https://github.com/mdn/content/pull/25002#issuecomment-1451678887

https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture

>Flaw count: 1
macros:
The fourth to sixth parameters of 'EmbedLiveSample' are deprecated

### Do you have any supporting links, references, or citations?

https://github.com/mdn/yari/blob/7bc71add7ef7349bd4dc207e4a7bd8b376f8e9b9/kumascript/macros/EmbedLiveSample.ejs#L4-L13

We should investigate usage of deprecated params for this macro, remove usage of them where possible, check if they are needed.

Additionally, the list of params starts at `$0` so the following "fourth to sixth" is actually "fifth to seventh":
https://github.com/mdn/yari/blob/7bc71add7ef7349bd4dc207e4a7bd8b376f8e9b9/kumascript/macros/EmbedLiveSample.ejs#L17-L23

__Additional info:__
To view these types of flaws, see http://localhost:5042/en-US/_flaws?search_flaws=macros%3AMacroDeprecatedError

**Comment by wbamberg** [comment]
That last parameter:

> //  $6 - (Deprecated) Allowed features, separated by semicolons (optional)

[I think was prematurely deprecated](https://github.com/mdn/yari/pull/6299#issuecomment-1238348298). It adds the given permissions to the `<iframe>`'s [`allow`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#allow) attribute, for when you want to demo things that need special powers. In this case if you remove `"display-capture"`, then in Chrome you get an error like:

> [Violation] Permissions policy violation: display-capture is not allowed in this document.

However! There are multiple other issues with this example.

There's an [assignment to `const` in the logging bit](https://github.com/mdn/content/blob/58c7d92148a52fd4654fb6633f9bd38b0cf0411b/files/en-us/web/api/screen_capture_api/using_screen_capture/index.md?plain=1#L200-L204), which completely stops the example from working. With that fixed, the example works, but the logging still doesn't work, because this:

```js
let logger = logElem.innerHTML;
console.log = (msg) => (logger += `${msg}<br>`);
console.error = (msg) => (logger += `<span class="error">${msg}</span><br>`);
console.warn = (msg) => (logger += `<span class="warn">${msg}<span><br>`);
console.info = (msg) => (logger += `<span class="info">${msg}</span><br>`);
```

...doesn't actually update the log element's contents. I'll file a PR to fix the logger anyway.

All this is Chrome. I can't get it to work at all in Firefox.

**Comment by wbamberg** [comment]
Filed https://github.com/mdn/content/pull/25185 for the other issues in the example.

**Comment by teoli2003** [comment]
Yes, I do agree that $6 was incorrectly deprecated.

$5 is strange too. It adds a class that is not used, but its presence leads to different results. I think there is a bug to fix before we can remove it.

**Comment by bsmth** [comment]
Thanks both for the investigation and follow-up improvements. Maybe we can transfer this issue over to Yari and use it to track 'remove deprecation warning for EmbedLiveSample params' for now. What do you think?

**Comment by teoli2003** [comment]
I would like to understand $5 before doing this.

**Comment by wbamberg** [comment]
>  its presence leads to different results

The difference is that you don't get [this](https://github.com/mdn/yari/blob/dd5b1a8b7f6e2985ccf713227029a3d06aeb63d3/client/src/document/index.scss#L319-L334), because `sample-code-frame` is not applied:

```css
  /* "Live Samples" discussion here:
  https://github.com/mdn/yari-private/issues/370,
  These src attributes taken from unsafe-html.js */
  &[src*="https://mdn.github.io"],
  &[src*="https://www.youtube-nocookie.com"],
  &[src*="https://jsfiddle.net"],
  &[src*="https://test262.report"],
  &.nobutton,
  &.sample-code-frame {
    background: #fff;
    border: 1px solid var(--border-primary);
    border-radius: var(--elem-radius);
    box-sizing: content-box;
    padding: 1rem;
    width: calc(100% - 2rem - 2px);
  }
```

What a shame that the discussion is secret :(.

The main visible difference is that you get `padding: 1rem` on the iframe. We could look for all cases where $5 is being passed and see if they would need adjustment without it.
