### ISSUE TITLE
Discourage "color: transparent" for "background-clip: text" 

### ISSUE THREAD

**Issue by myfonj** [mdn/content#2638]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip

#### TL;DR:
- `color: transparent` is dangerous, maybe mention feature detection or propose text-fill-color instead;
- where is `background-image:`, there should be `background-color:`;
- especially when clipped into text.

#### What information was incorrect, unhelpful, or incomplete?

Code snippets use `color: transparent` or nearly transparent black for demonstrations of `background-clip: text`, with no support detection or other practice to preserve backward compatibility and fail-safe accessibility.  It sounds reasonable for demonstrative purposes, but is dangerous for UAs without proper support and for scenarios when decorative background image rendering fails for any reason.  MDN should at least warn about such things, or better provide best-practice solution.

#### Specific section or headline?

Intro and Examples.

#### What did you expect to see?

`color: transparent`  substituted with `-webkit-text-fill-color: transparent` or even better wrapped in `@supports` block in snippets. Plus concrete `color` and `background-color` fallback declarations. Or warning.

I know situation is complicated because there is no standard un-prefixed `text-fill-color` ATM but i guess all browsers supporting `-webkit-background-clip: text` supports `-webkit-text-fill-color`. (From compat tables stands out only Safari 3 (year ~2009) not supporting ..text-fill-color but supporting ..background-clip: text; cannot verify and have no clue how to cope with this, since `@supports` apparently came to Safari in v.9 (~2016).)

The thing is, I am not even sure what the best practice would be here and where to put it in the page.  I tried to make truly resilient snippet preserving readability and contrast in UAs without support of modern CSS and with failing resources in mind, but resulting code looks quite bloated: https://codepen.io/myf/pen/zYoPJam?editors=1100, try to cripple rules to simulate failed resources or lack CSS of support:

```CSS

/* 
 - assumed dark text on bright background;
 - gradients in background-images are illustrative as "external resources that could fail or be blocked"
*/

/* § ancient / fallback / default
*/

p {
	background-color: pink;
	background-image: repeating-linear-gradient(white, pink 0.5em, white 1em);
	color: black;
}

/* § modern / fancy / extra
*/

@supports (-webkit-background-clip: text) and (-webkit-text-fill-color: transparent) {
	p {
		background-color: black;
		background-image: none;
		/* in case following image failed, previous reset is needed to negate the legacy bright one
		*/
		background-image: repeating-radial-gradient(black, darkred 0.5em, black 1em);
		color: white;
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		/* color: transparent should be safe here as well,
		 but I just cannot supress all those red flags seeing `color: transparent` on important content
		*/
	}
}

```

Sorry for half-baked solution and murky guesswork about actual best practices.  As demonstrated, I couldn't propose consistent solution, but I really had to vent this itch.

#### Did you test this? If so, how?

From compat data It is clearly apparent that current examples would produce invisible text in IE.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/background-clip`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/background-clip/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>
