### ISSUE TITLE
cant see red thumb and an orange track as mentioned in the scrollbar explanation

### ISSUE THREAD

**Issue by jo777750** [mdn/content#26654]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars

### What information was incorrect, unhelpful, or incomplete?

in EDGE Version 113.0.1774.35 (Official build) (64-bit),I cant see red thumb and an orange track as mentioned in the content explanation

### What did you expect to see?

a red thumb and an orange track as mentioned in the content explanation

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_scrollbars`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_scrollbars/index.md
* Last commit: https://github.com/mdn/content/commit/2b16c34a185fdf37b0a136e90642147ff046588c
* Document last modified: 2023-04-29T10:19:37.000Z

</details>

**Comment by hh-shiung** [comment]
![image](https://github.com/mdn/content/assets/5265947/74b6d2c1-ba83-4912-b619-f3575fc4dae8)

Does not show on Microsoft Edge.

Requires additional `::-webkit-scrollbar` postfix to `.poem` class to have an effect on WebKit browsers.

Recommended update:

```css
/* hidden css */
.poem {
  width: 300px;
  height: 100px;
  border: 1px solid;
  overflow: scroll;
}

/* Example CSS */
.poem::-webkit-scrollbar {
  width: 24px;
  height: 24px;
  background-color: orange;
}

.poem::-webkit-scrollbar-thumb {
  background-color: red;
}
```
