### ISSUE TITLE
:blank don't work on textarea

### ISSUE THREAD

**Issue by MathGoOli** [mdn/content#28619]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:blank

### What specific section or headline is this issue about?

example

### What information was incorrect, unhelpful, or incomplete?

:blank don't work on textarea. I've tested on Mozilla and Chrome. but its work on other tags like <p>

### What did you expect to see?

try, html

```html
<div class="blanks">
  <p>This paragraph is not empty or blank.</p>
  <p><!--this is empty and blank --></p>
  <p>
    
    <!-- this is not empty, because it has whitespace. But it is blank.-->
    
  </p>
  <p>This paragraph is not empty or blank.</p>
</div>

```
css

```css

p {
  min-height: 30px;
  width: 250px;
  background-color: lightblue;
}

p:blank { display: none; }

p:-moz-only-whitespace { display: none; } /* Mozilla-only pseudo-class that works like :blank will */

```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_blank`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:blank
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_blank/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>
