### ISSUE TITLE
Tips in the code

### ISSUE THREAD

**Issue by 11AMER** [mdn/content#29175]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter

### What specific section or headline is this issue about?

Starting point

### What information was incorrect, unhelpful, or incomplete?

In the CSS file we should give some styles of the p element to the `<time class="sender-column">` element,
So we can put the date direct inside it instead of nesting a p element inside this time element which is not semantically!

### What did you expect to see?

```css
body {
  max-width: 800px;
  margin: 0 auto;
}

.sender-column {
  text-align: right;
}

time.sender-column {
  display: block;
  margin: 1em 0;
}

h1 {
  font-size: 1.5em;
}

h2 {
  font-size: 1.3em;
}

p,
ul,
ol,
dl,
address,
time.sender-column {
  font-size: 1.1em;
}

p,
li,
dd,
dt,
address,
time.sender-column {
  line-height: 1.5;
}
```

### Do you have any supporting links, references, or citations?

Check this in the W3C HTML Validator:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test</title>
</head>
<body>
  <time datetime="2016-01-20" class="sender-column"><p>20 January 2016</p></time>
</body>
</html>
```

Will cause:
Error: Element [p] not allowed as child of element [time] in this context.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/marking_up_a_letter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/marking_up_a_letter/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>
