### ISSUE TITLE
Nesting selector: possible confusion between child rule and child selector

### ISSUE THREAD

**Issue by jb222** [mdn/content#29744]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector

### What specific section or headline is this issue about?

Syntax example

### What information was incorrect, unhelpful, or incomplete?

`.parent-rule:hover {
  /* child rule properties */
}`

### What did you expect to see?

Trying to understand the logic, I guess it should be:
`.parent-rule:hover {
  /* parent rule properties on hover */
}`

### Do you have anything more you want to share?

Better check all examples on the page...

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/nesting_selector`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/nesting_selector/index.md
* Last commit: https://github.com/mdn/content/commit/2dfefb1943c8a6c88864ee71f605db27405e3857
* Document last modified: 2023-10-17T19:50:04.000Z

</details>

**Comment by OnkarRuikar** [comment]
In this case of `&`, child rule here doesn't mean rule for child element.\
Here,\
`.parent{ &.child{}}` is equivalent to `.parent.child{}`.
`.parent{ .child{}}`&nbsp;&nbsp; is equivalent to `.parent .child{}`.\
Note the missing space in equivalents in both cases.

Child rule doesn't mean child element selector. Consider the same demo code with actual properties:
```css
.parent-rule {
  /* parent rule properties */
  color:red;

  &:hover {
    /* child rule properties */
    font-size: 1rem;
  }
}

/* the browser parses this as */
.parent-rule {
  /* parent rule properties */
  color: red;
}

.parent-rule:hover {
  /* child rule properties */
  font-size: 1rem;
}
```
Your commend would mean:
```css
.parent-rule:hover {
  /* parent rule properties on hover *
  color: red;
}
```
