### ISSUE TITLE
Unhelpful using of  `&`.

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#29799]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators

### What specific section or headline is this issue about?

Creating complex selectors with nesting

### What information was incorrect, unhelpful, or incomplete?

```css
h1 {
  & ~ p { /* this is parsed by the browser as h1 ~ p */
    font-weight: bold;
    background-color: #333;
    color: #fff;
    padding: .5em;
  }
}
```

In the Interactive editor which (&) just add an extra white space because it will not act as a descendant combinator the ~ what will be the subsequent-sibling combinator

### What did you expect to see?

```css
h1 {
  ~ p { /* this is parsed by the browser as h1 ~ p */
    font-weight: bold;
    background-color: #333;
    color: #fff;
    padding: .5em;
  }
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/combinators`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/combinators/index.md
* Last commit: https://github.com/mdn/content/commit/bb652aaf3e38f3c7fef970a62f813047dffac879
* Document last modified: 2023-10-02T11:11:40.000Z

</details>
