### ISSUE TITLE
Any PR with "dangerous" edits should be considered dangerous

### ISSUE THREAD

**Issue by peterbe** [mdn/content#2985]
Security scenario: Someone makes a PR that covers lots and lots of files. They might all look like harmless typo fixes in various `index.html` files. But they could also try to sneak in a change to `.github/workflows/pr-testing.yml` that disables something in the workflow that checks for unsafe things. For example:
```diff
-         export BUILD_FLAW_LEVELS="*:ignore, unsafe_html: error"
+         export BUILD_FLAW_LEVELS="*:ignore, unsafe_html: ignore"
```
Another example is that they might mess with `yarn.lock` so that it changes something like this:
```diff
-camelcase@^2.0.0:
   version "2.1.1"
-  resolved "https://registry.yarnpkg.com/camelcase/-/camelcase-2.1.1.tgz#7c1d16d679a1bbe59ca02cacecfb011e201f5a1f"
   integrity sha1-fB0W1nmhu+WcoCys7PsBHiAfWh8=
+camelcese@^2.0.0:
   version "2.1.1"
+  resolved "https://registry.notyarnpkg.com/camelcase/-/camelcase-2.1.1.tgz#7c1d16d679a1bbe59ca02cacecfb011e201f5a1f"
   integrity sha1-fB0W1nmhu+WcoCys7PsBHiAfWh8=
``

If this happens, the reviewer should be as helped as possible to avoid missing this. Probably safest to just break the build so that only an admin can merge it. The hope and assumption is that seeing the red X on the checks should alert even the admins to not be too quick to merge.

**Comment by peterbe** [comment]
We'll need to assume that when `dependabot[bot]` makes PRs (for example https://github.com/mdn/content/pull/2979 or https://github.com/mdn/content/pull/2770) that they're OK and safe. 
Note, for `dependabot`, they have write access to the repo so they push their branches to `mdn/content` instead of a fork. So instead of looking for `username === 'dependabot'` we can make the checking depend on it coming from a fork.

**Comment by peterbe** [comment]
@nschonni Do you have some ideas for implementation here? I was thinking something like this:

```yml
name: Markdown Docs files

on:
  pull_request:
    paths:
      - scripts/*
      - package.json
      - yarn.lock
      - .github/workflows/*
jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Stop anything
         run: |
           echo "Any PR that edits these files should break the build and expect admin overrides"
           exit 1
```

Do you have any good suggestions for checking if it's coming from a fork or not? (...to solve the problem of letting `dependabot` PRs roll)
