### ISSUE TITLE
Appended nesting selector example

### ISSUE THREAD

**Issue by wtflm** [mdn/content#30237]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting

### What specific section or headline is this issue about?

Appending nesting selector

### What information was incorrect, unhelpful, or incomplete?

I think there is an issue with the comment explaining the final nested rule of the featured card example:

```css
.card {
	padding: 0.5rem;
	border: 1px solid black;
	border-radius: 0.5rem;
	& h2 {
		/* equivalent to `.card h2` */
		color: slateblue;
		.featured & {
			/* equivalent to `.featured .card h2` */
			color: tomato;
		}
	}
}
```
>```/* equivalent to `.featured .card h2` */```

### What did you expect to see?

I'm trying to learn how this stuff works but the equivalency doesn't seem to check out. If written like that without nesting, it suggests a document structure like
```html
<div class="featured">
	<article class="card">
		<h2></h2>
	</acticle>
</div>
```

instead of the

```html
<article class="card featured">
	<h2></h2>
</article>
```

seen in the example. The CSS works but I'm trying to figure out how exactly. I'm not seeing how the nested rules produce something equivalent to `.featured.card h2`, which is what the effective rule seems to be judging by how swapping the order of it and the nested selector in CSS makes the output behave.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_nesting/using_css_nesting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_nesting/using_css_nesting/index.md
* Last commit: https://github.com/mdn/content/commit/dac4c90aac5449d2f0adeccd324d4a0aae457d57
* Document last modified: 2023-10-13T20:14:13.000Z

</details>
