### ISSUE TITLE
No information on border-color  <stripes()>

### ISSUE THREAD

**Issue by Akindin** [mdn/content#32234]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/border-right-color

### What information was incorrect, unhelpful, or incomplete?

No examples, or compatibility data on  <stripes()>

### What did you expect to see?

Examples of usage of stripes

### Do you have any supporting links, references, or citations?

https://drafts.csswg.org/css-images-4/#stripes

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/border-right-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/border-right-color
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/border-right-color/index.md
* Last commit: https://github.com/mdn/content/commit/1c4eb0bfb5f72a26fcc21a83fac91aa3e66c2fb8
* Document last modified: 2024-01-02T16:00:45.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising, there's an example here: https://drafts.csswg.org/css-borders-4/#example-7b0dea52

e.g.;

```css
.bar {
  border: 30px solid;
  border-color: stripes(black, white);
}

.foo {
  border: 30px solid;
  border-color: stripes(dodgerblue, skyblue) stripes(yellow, gold) stripes(lightgreen, limegreen) stripes(indianred, orange);
}
```

This is not yet implemented anywhere (and is marked [not ready for implementation](https://drafts.csswg.org/css-borders-4/)), so we will be waiting until there is signals it is shipping before documenting it.
