### ISSUE TITLE
Document how to use palette-mix() and its browser support

### ISSUE THREAD

**Issue by foolip** [mdn/content#32308]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-palette

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/font-palette#formal_syntax

### What information was incorrect, unhelpful, or incomplete?

The `palette-mix()` function is mentioned in the syntax, but not how to use it.

### What did you expect to see?

Documentation that `palette-mix()` is used for animations of the `font-palette` property, defining a mix of two palettes in some interpolation color space.

### Do you have any supporting links, references, or citations?

https://chromestatus.com/feature/5177171439517696

**Comment by foolip** [comment]
I'm adding this to BCD in https://github.com/mdn/browser-compat-data/pull/22242.

**Comment by chrisdavidmills** [comment]
Hi @foolip! There seems to be a bit of confusion here, which I'm hoping to clear up as I start to work on content for this.

https://chromestatus.com/feature/5177171439517696 refers to animating `font-palette`, yes, but it doesn't mention `palette-mix()` at all. And if you look at the animation example just below https://drafts.csswg.org/css-fonts/#typedef-font-palette-palette-mix, it animates smoothly between two values of `font-palette`.

`palette-mix()` seems to be something different — a way to create a new palette by mixing two other palettes. It seems to work in chrome Canary. I got the following to work:

```css
    @import url('https://fonts.googleapis.com/css2?family=Nabla&display=swap');

    @font-palette-values --pink {
      font-family: Nabla;
      base-palette: 1;
    }

    @font-palette-values --yellow {
      font-family: Nabla;
      base-palette: 7;
    }

    p {
      font-family: "Nabla";
      font-size: 5rem;
      text-align: center;
      font-palette: palette-mix(in lch, --pink, --yellow);
    }
```

Do you know if there is a separate ChromeStatus entry for `palette-mix()`?
