### ISSUE TITLE
font-weight page doesn't explain whether it is possible to set a range, or if so, how

### ISSUE THREAD

**Issue by MarjaE2** [mdn/content#32619]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight

### What specific section or headline is this issue about?

It's an overall issue

### What information was incorrect, unhelpful, or incomplete?

1. It doesn't explain whether it is possible for users to set a range. For example, users who have trouble reading thin text may want to set a minimum font-weight, without forcing all text to the same weight.
2. If that is possible, it doesn't explain how.
3. It mentions "multiple values" but doesn't explain if these set a range, and doesn't explain what else they do.
4. If multiple values are *supposed* to set a range, then in Firefox they are ignored as an error.

### What did you expect to see?

Information for users to set font-weight so that more pages will be readable.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@font-face/font-weight`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@font-face/font-weight/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by OnkarRuikar** [comment]
There are two pages titled `font-weight` on MDN:
1. https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight
2. https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight

The first one, which [takes only one value](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#formal_syntax), is a property that is applied on elements in html:
```css
div {
  font-weight: bold;
  font-weight: 100;
}
```

The second one, which [can take two values](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight#formal_syntax), is applied only in context of the [`@font-face` at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face):
```css
/* font definition */
@font-face {
  font-family: "MyCoolFont";
  src: url(./assets/fonts/my_cool_font.woff2);
  font-weight: 600 900;  /* here the range tells browser to select this font if weight lies in between 600-900 */
}

/* font use */
div {
  font-family: "MyCoolFont";
  font-weight: 700; /* here we tell browser that we want text of 700 weight */
}
```
You can [play with it on MDN playground](https://developer.mozilla.org/en-US/play?id=KedfXRDzPn0HLbW4mc2hNCRUz7RQDzaGHeVPC%2B1dcwkHE2tTR%2FhD1QfX7s11XqVCgBViOzIFL3KrbWk1).

***
Perhaps you meant to look at the first page [`CSS/font-weight`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight). To avoid the confusion we better use a different title for `@font-face/font-weight` page something like `@font-face: font-weight`.
