### ISSUE TITLE
If you set the % unit for max-height, css is not applied.

### ISSUE THREAD

**Issue by callor** [mdn/content#35018]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/max-height

### What specific section or headline is this issue about?

max-height

### What information was incorrect, unhelpful, or incomplete?

MDNIt applies to MDN, but does not apply to general HTML, testing on w3schools.com, etc.

### What did you expect to see?

max-height : 50%; or max-height : calc(100% - 100px); I hope the effect of

### Do you have any supporting links, references, or citations?

 no

### Do you have anything more you want to share?

no

**Comment by OnkarRuikar** [comment]
Could you provide a minimum reproducible code?
For percentage values to work on any item, at least one of its ancestors needs to have fixed height explicitly set. Refer [this demo](https://developer.mozilla.org/en-US/play?id=M2hMYm%2BWd9SAyyTxpmWwymhfltAzSLY%2FYNb7uLeEMQ3k0uTZMvBLXY0OBqLmKTPfGvU2SL7syUvfSt8K).

[The cyclic percentage size in CSS height / width / max-height / max-width](https://medium.com/@dpang06/the-cyclic-percentage-size-in-css-height-width-max-height-max-width-2094ecc7bd93) article has a better explanation on this.

**Comment by callor** [comment]
```html
<section class="main">
	<h2>Student List</h2>
	<table class="student list">
		<thead>
			<tr>
				<th>Number</th>
				<th>Name</th>
				<th>Dept</th>
				<th>Grade</th>
				<th>tel</th>
				<th>addr</th>
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${ST_LIST}" var="ST">
				<tr data-st_num="${ST.st_num}">
					<td>${ST.st_num}</td>
					<td>${ST.st_name}</td>
					<td>${ST.st_dept}</td>
					<td>${ST.st_grade}</td>
					<td>${ST.st_tel}</td>
					<td>${ST.st_addr}</td>
				</tr>
			</c:forEach>
		</tbody>
	</table>
	<div>
		<a href="${rootPath}/insert">Insert Student</a>
	</div>
</section>
```
```css
@charset "UTF-8";
section.main {
  width: 100%;
  height: calc(100%);
  background-color: #eee;
  text-align: center;

  h2,
  table,
  div {
    width: 85%;
    margin: 10px auto;
  }
  h2 {
    border: 1px solid #aaa;
  }

  table {
    border-collapse: collapse;

   
    tbody {
      display: block !important;
      max-height: calc(100vh - 200px - 80px - 50px);
      overflow-y: auto;
   
      scrollbar-width: none;
 
      tr:nth-of-type(odd) {
        background-color: #ddd;
      }
      tr:hover {
        background-color: #fff;
        cursor: pointer;
      }
    }

    thead,
    tbody tr {
      display: table;
      width: 100%;
    }
    thead,
    tbody {
      width: 100%;
    }
    thead tr,
    tbody tr {
      display: flex !important;
      justify-content: space-between;
    }

    td,
    th {
      border: 1px solid #aaa;
      padding: 5px 12px;
      text-align: left;
      flex: 1;
      &:nth-of-type(6) {
        flex: 2;
      }
    }
  }
  div a {
    display: inline-block;
    padding: 12px 16px;
    background-color: blue;
    border-radius: 15px;
    color: white;
    &:hover {
      cursor: pointer;
      background-color: #777;
    }
  }
}
```
