### ISSUE TITLE
First example on relative CSS colors is broken

### ISSUE THREAD

**Issue by danrr** [mdn/content#35479]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors

### What specific section or headline is this issue about?

general_syntax

### What information was incorrect, unhelpful, or incomplete?

The first set of snippets on the page gets picked up together when "Open in playground" is clicked on the first example.
It results in the following CSS
```css
color-function(from origin-color channel1 channel2 channel3)
color-function(from origin-color channel1 channel2 channel3 / alpha)

/* color space included in the case of color() functions */
color(from origin-color colorspace channel1 channel2 channel3)
color(from origin-color colorspace channel1 channel2 channel3 / alpha)

#container {
  display: flex;
  width: 100vw;
  height: 100vh;
  box-sizing: border-box;
}

.item {
  flex: 1;
  margin: 20px;
}

#one {
  background-color: red;
}

#two {
  background-color: rgb(from red 200 g b);
}

red
rgb(255 0 0)
rgb(from red r g b)
rgb(from red 255 g b)
rgb(from red 255 0 0)
```

This includes two additional CSS snippets and does not display correctly in the embedded preview or in the stand-laone playground.

### What did you expect to see?

```css
#container {
  display: flex;
  width: 100vw;
  height: 100vh;
  box-sizing: border-box;
}

.item {
  flex: 1;
  margin: 20px;
}

#one {
  background-color: red;
}

#two {
  background-color: rgb(from red 200 g b);
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_colors/relative_colors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_colors/relative_colors/index.md
* Last commit: https://github.com/mdn/content/commit/4e508e2f543c0d77c9c04f406ebc8e9db7e965be
* Document last modified: 2024-07-26T14:38:02.000Z

</details>
