### ISSUE TITLE
Issue with "all": (all does not reset Custom Properties!)

### ISSUE THREAD

**Issue by MenaiAla** [mdn/content#3646]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/all

#### What information was incorrect, unhelpful, or incomplete?

You have mentioned that `all` resets all properties except `unicode-bidirection` and `Custom CSS Properties`.

However, when I tried using `CSS Variables`, I've found that it resets them. I get confused  because I did not find a helpful example with `Custom Properties`.

#### Specific section or headline?

In the defintion of `all` property.

#### What did you expect to see?

I expected that `all` does not reset `Custom Properties`

#### Did you test this? If so, how?

**HTML**

```html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="index.css" />
  </head>
  <body>
    <div class="container">
      <div class="box">1</div>
      <div class="box align-self">2</div>
      <div class="box" style="height: 50px">3</div>
    </div>
    <script src="index.js"></script>
  </body>
</html>

```

```css
:root {
  --dark-color: #222;
}
.container {
  display: flex;
  height: 400px;
  background-color: var(--dark-color);
  flex-wrap: wrap;
  align-items: center;
  all: unset;
}
.box {
  width: 100px;
  background-color: blueviolet;
}
.align-self {
  align-self: flex-end;
}

```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/all`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/all
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/all/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>
