### ISSUE TITLE
An explanation is needed for what happens If no eligible query container is available

### ISSUE THREAD

**Issue by juner** [mdn/content#38875]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries

### What specific section or headline is this issue about?

Container query length units

### What information was incorrect, unhelpful, or incomplete?

> When applying styles to a container using container queries, you can use container query length units. These units specify a length relative to the dimensions of a query container. Components that use units of length relative to their container are more flexible to use in different containers without having to recalculate concrete length values.

### What did you expect to see?

If no eligible query container is available, then use the small viewport size for that axis.

### Do you have any supporting links, references, or citations?

> If no eligible query container is available, then use the [small viewport size](https://drafts.csswg.org/css-values-4/#small-viewport-size) for that axis.

https://drafts.csswg.org/css-conditional-5/#container-lengths

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_containment/container_queries`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_containment/container_queries/index.md
* Last commit: https://github.com/mdn/content/commit/a69f9903e7444d42adcf2432eaa511c05761c757
* Document last modified: 2025-03-07T00:57:54.000Z

</details>

**Comment by juner** [comment]
For example, in this sample, `.main-3` does not have a parent container query, but the `cqh` used is calculated based on the `small viewport size`.

```html
<main class="type-1">
  <div class="main-1"></div>
  <div class="main-2"></div>
</main><main class="type-2">
  <div class="main-3"></div>
  <div class="main-4"></div>
</main>
```

```css
main {
  &.type-1 {
    padding: 1em;
    height: calc(50vh - 1em);
    container-type: size;
    .main-1 {
      /* ↓ The most recent container is .type-1, so we calculate from there. */
      height: 25cqh;
    }
    /* ↓ .type-1 is a container, so it works */
    @container (block-size >= 0) {
      .main-2 {
        height: 25cqh;
      }
    }
  }
  &.type-2 {
    padding: 1em;
    height: calc(50vh - 1em);
    .main-3 {
      /* ↓If there is no immediate container, it will be calculated as svh equivalent for a small viewport. */
      height: 25cqh;
    }
    /* ↓ .type-2 is not a container, so it doesn't work. */
    @container (block-size >= 0) {
      .main-4 {
        height: 25cqh;
      }
    }
  }
}
```

https://codepen.io/juner/pen/YPzONJG
