### ISSUE TITLE
Understanding aspect-ratio example is confusing

### ISSUE THREAD

**Issue by yinhx3** [mdn/content#39077]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_sizing/Understanding_aspect-ratio

### What specific section or headline is this issue about?

Creating a circle based on the container size

### What information was incorrect, unhelpful, or incomplete?

In this [Play](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_sizing/Understanding_aspect-ratio#common_aspect-ratio_use_cases:~:text=0%3B%0A%7D-,Play,-Common%20aspect%2Dratio), `display: flex` is set, cause the height of two balls always the same. 

For example, I change the style of the first ball:
```css
div:first-of-type {
  /* overflow: hidden; */
}
```
and the second ball change, which may confuse readers, because 
```css
div:last-of-type p {
  margin-block: 0;
}
```
doesn't have any change.

### What did you expect to see?

Use 
```css
section {
  display: flex;
  place-items: center;
  gap: 20px;  
}
```
or
```css
section {
  gap: 20px;
}

div {
  display: inline-block;
  width: 200px;
  padding: 5px;
  background-color: #66ccff;
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_box_sizing/understanding_aspect-ratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_sizing/Understanding_aspect-ratio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
* Last commit: https://github.com/mdn/content/commit/ad896488bf8fac04fc6fa144c441fdbfd880737c
* Document last modified: 2025-03-10T19:31:21.000Z

</details>
