### ISSUE TITLE
CSS counter example is misleading

### ISSUE THREAD

**Issue by Akiyamka** [mdn/content#39079]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_counter_styles/Using_CSS_counters

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_counter_styles/Using_CSS_counters#displaying_a_counter

### What information was incorrect, unhelpful, or incomplete?

This code in example are incorrect
```css
h3::before {
  counter-increment: section; /* Increment the value of section counter by 1 */
  content: "Section " counter(section) ": "; /* Display counter value in default style (decimal) */
}
```
It will render counters as
```
1.
1.
1.
```

### What did you expect to see?

Most likely writer means 
 ```css
h3 {
  counter-increment: section; /* Increment the value of section counter by 1 */
}

h3::before {
  content: "Section " counter(section) ": "; /* Display counter value in default style (decimal) */
}
```

### Do you have any supporting links, references, or citations?

Demo:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      body {
        background: black;
        padding: 0 24px;
        margin: 0;
        height: 100vh;
        color: white;
        display: flex;
        flex-flow: column nowrap;
        gap: 16px;
        justify-content: center;
        align-items: center;
      }
    
      /* Bad */
      .wrong-list .counter::before {
        counter-increment: section;
        content: 'Section ' counter(section) ': ';
      }
      
      /* Good */
      .correct-list .counter {
        counter-increment: section;
      }
      
      .correct-list .counter::before {
        content: 'Section ' counter(section) ': ';
      }
    </style>
  </head>
  <body>
    <div class="wrong-list">
      <div class="counter">Foo</div>
      <div class="counter">Bar</div>
      <div class="counter">Baz</div>
    </div>
     <div class="correct-list">
      <div class="counter">Foo</div>
      <div class="counter">Bar</div>
      <div class="counter">Baz</div>
    </div>
  </body>
</html>



```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_counter_styles/using_css_counters`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_counter_styles/Using_CSS_counters
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_counter_styles/using_css_counters/index.md
* Last commit: https://github.com/mdn/content/commit/44f398527f2b0195a7c3b35db0a53c80aebe8e48
* Document last modified: 2025-03-31T01:25:00.000Z

</details>
