### ISSUE TITLE
There is an error in the description of the "Baseline Badge" on the `Object.hasOwn` page

### ISSUE THREAD

**Issue by yurano** [mdn/content#39248]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn

### What specific section or headline is this issue about?

Baseline Badge

### What information was incorrect, unhelpful, or incomplete?

The "Baseline Badge" on this page indicates that the feature is Widely available, but this appears to be incorrect.
Object.hasOwn() seems to be supported in major browsers only from March 2022 onward.

### What did you expect to see?

The baseline badge should indicate Baseline 2022 instead.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/hasown`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/hasown/index.md
* Last commit: https://github.com/mdn/content/commit/3dbbefa32758e2a1ca9a37c2788370c06aae2738
* Document last modified: 2025-03-06T15:48:08.000Z

</details>

**Comment by caugner** [comment]
This stems from the fact that the Baseline banner is currently driven by the feature **group**'s Baseline status (see [here](https://github.com/web-platform-dx/web-features/blob/6b621c4f4763ef3e6b41586378533ef180a9ee57/features/object-object.yml.dist#L4-L15)):

```yml
status:
  baseline: high
  baseline_low_date: 2015-07-29
  baseline_high_date: 2018-01-29
  support:
    chrome: "1"
    chrome_android: "18"
    edge: "12"
    firefox: "1"
    firefox_android: "4"
    safari: "1"
    safari_ios: "1"
```

Instead, we should use the feature's "by key" Baseline status (see [here](https://github.com/web-platform-dx/web-features/blob/6b621c4f4763ef3e6b41586378533ef180a9ee57/features/object-object.yml.dist#L295-L306)):

```yml
  # baseline: high
  # baseline_low_date: 2022-03-14
  # baseline_high_date: 2024-09-14
  # support:
  #   chrome: "93"
  #   chrome_android: "93"
  #   edge: "93"
  #   firefox: "92"
  #   firefox_android: "92"
  #   safari: "15.4"
  #   safari_ios: "15.4"
  - javascript.builtins.Object.hasOwn
```
