### ISSUE TITLE
Issue with "Legacy layout methods": links to non-existent grids/flexbox-grid.html page; should be Legacy_Layout_Methods#flexbox_grids?

### ISSUE THREAD

**Issue by kh1925** [mdn/content#9301]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods

#### What information was incorrect, unhelpful, or incomplete?
Two links refers to a wrong CSS code :
  1/The flexbox-grid.html (https://github.com/mdn/learning-area/blob/master/css/css-layout/grids/flexbox-grid.html)
  2/its live example (https://mdn.github.io/learning-area/css/css-layout/grids/flexbox-grid.html)

#### Specific section or headline?
Section: "Flexbox grids?"
Link: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods#flexbox_grids

#### What did you expect to see?
I expected to see only the code showcased in the "Flexbox grids?" :

```css
body {
  width: 90%;
  max-width: 980px;
  margin: 0 auto;
}

.wrapper {
  padding-right: 2.08333333%;
}

.row {
  display: flex;
}

.col {
  margin-left: 2.08333333%;
  margin-bottom: 1em;
  width: 6.25%;
  flex: 1 1 auto;
  background: rgb(255,150,150);
}
```
 

#### Did you test this? If so, how?
yes, I tested and the code is not appropriate with the explanation.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/legacy_layout_methods`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/legacy_layout_methods/index.html
* Last commit: https://github.com/mdn/content/commit/b7c594e7a8e5eb31a70bcf3e07d931e4603d201b
* Document last modified: 2021-09-03T05:34:55.000Z

</details>

**Comment by bsmth** [comment]
hi @kh1925, thanks a lot for your report.

I'm going to close this issue as it looks like the problem is resolved. Navigating to https://github.com/mdn/learning-area/blob/main/css/css-layout/grids/flexbox-grid.html showcases the CSS you are referencing:

```css
body {
      width: 90%;
      max-width: 980px;
      margin: 0 auto;
    }

    .wrapper {
      padding-right: 2.08333333%;
    }
    
    .row {
      display: flex;
    }

    .col {
      margin-left: 2.08333333%;
      margin-bottom: 1em;
      width: 6.25%;
      flex: 1 1 auto;
      background: rgb(255,150,150);
    }
```

If you think I am closing this by mistake, feel free to reopen or leave a comment explaining why you think so.

Thank you. :)
