### ISSUE TITLE
Issue with grid: (min-width: 63.9385em)

### ISSUE THREAD

**Issue by h9lk** [mdn/content#9612]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

#### What information was incorrect, unhelpful, or incomplete?
This's problem with svg icons. As far as understand, this problem occurs wherever there are long names, but did not check it.

#### Specific section or headline?
```html
<nav id="sidebar-quicklinks" class="sidebar"><nav>
```
and css rule

```css
@media (min-width: 63.9385em)
.page-wrapper.document-page {
    grid-template-columns: minmax(25%,75%) minmax(75%,25%);
    grid-template-rows: repeat(3,auto) -webkit-max-content 1fr;
    grid-template-rows: repeat(3,auto) max-content 1fr;
}
```
#### What did you expect to see?
![1](https://user-images.githubusercontent.com/32390006/136173889-75b938d4-cf7d-4f18-89ba-bc23dd6b65a1.png)

#### Did you test this? If so, how?
made changes in css grid percentage ratio and think this is correct
```css
@media (min-width: 63.9385em)
.page-wrapper.document-page {
    grid-template-columns: minmax(35%, 65%) minmax(65%, 35%);
}
```
or

```css
@media (min-width: 63.9385em)
.page-wrapper.document-page {
    grid-template-columns: 35% 65%;
}
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/index.md
* Last commit: https://github.com/mdn/content/commit/9e7347af24ffb941643d365fe36c05c3bd21b633
* Document last modified: 2021-09-03T15:24:53.000Z

</details>
